version: '3.2'

services:
  test:
    image: slack-commands
    build:
      context: .
      cache_from:
        - slack-commands
        - $IMAGES_DOMAIN/slack-commands
    command: yarn coveralls
    environment:
      COVERALLS_REPO_TOKEN:

  deploy:
    image: slack-commands
    build:
      context: .
      cache_from:
        - slack-commands
        - $IMAGES_DOMAIN/slack-commands
    command: yarn deploy
    environment:
      LAMBDA_ROLE:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      JENKINS_API_KEY:
      JENKINS_USERNAME:
      REST_API_ID:
      REST_API_ROOT_RESOURCE_ID:
      REST_API_NAMESPACE_RESOURCE_ID: