version: '3.7'

services:
  test:
    image: slack-commands
    build:
      context: .
      cache_from:
        - slack-commands
        - $IMAGES_DOMAIN/slack-commands
    command: yarn coverage
    environment:
      COVERALLS_REPO_TOKEN:

  deploy:
    image: slack-commands
    build:
      context: .
      cache_from:
        - slack-commands
        - $IMAGES_DOMAIN/slack-commands
    command: yarn deploy --stage=${STAGE} --region=${REGION}
    environment:
      LAMBDA_ROLE:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      REST_API_ID:
      REST_API_ROOT_RESOURCE_ID:
      REST_API_NAMESPACE_RESOURCE_ID:
      REGION:
      STAGE:
      S3_BUCKET:
      # LAMBDA SECRETS
      JENKINS_API_KEY:
      JENKINS_USERNAME:
      AUTH_TOKEN: