service: web-lambdas-slack-commands
provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs8.10
  role: ${env:LAMBDA_ROLE}
  apiName: web-lambdas-${opt:stage, 'dev'}
  stage: ${opt:stage, 'dev'}
  environment:
    JENKINS_API_KEY: ${env:JENKINS_API_KEY}
    JENKINS_USERNAME: ${env:JENKINS_USERNAME}
  deploymentBucket:
    name: nyulibraries-web-lambdas-${opt:stage, 'dev'}
  deploymentPrefix: ${self:service}-${opt:stage, 'dev'}
  apiGateway:
    restApiId: ${env:REST_API_ID}
    restApiRootResourceId: ${env:REST_API_ROOT_RESOURCE_ID}
    restApiResources:
      '/slack-commands': ${env:REST_API_NAMESPACE_RESOURCE_ID} # ID for '/slack-commands' resource

package:
  include:
    - handler.js
  exclude:
    - docker-compose*
    - Dockerfile*

functions:
  campusmedia:
    name: ${self:service}-campusmedia-${opt:stage, 'dev'}
    events:
      - http:
          method: get
          path: slack-commands/campusmedia
    handler: handler.campusmedia
    memorySize: 1024